//! kwconf-style CLI and config resolution for Rust.
//!
//! The runtime keeps one small contract:
//!
//! ```text
//! defaults < config file < env < argv
//! ```
//!
//! Parsers apply to string-only sources: argv and env.

use clap::builder::styling::{AnsiColor, Effects, Styles};
use clap::{Arg, ArgAction, Command};
use clap_complete::aot::{generate, Shell};
use serde::de::DeserializeOwned;
use serde::Serialize;
use serde_json::{Map, Value};
use std::collections::BTreeMap;
use std::env;
use std::ffi::OsString;
use std::fmt;
use std::path::{Path, PathBuf};

pub use clap::ColorChoice;
pub use clap::ColorChoice as HelpColorChoice;
pub use clap_complete::aot::Shell as CompletionShell;
pub use kwconf_derive::{Config, ModalConfig};

/// Result type used by kwconf-rs.
pub type Result<T> = std::result::Result<T, Error>;

/// A derived config object.
pub trait Config: Default + Serialize + DeserializeOwned + Sized {
    /// Static metadata generated by the derive macro.
    fn config_spec() -> &'static ConfigSpec;

    /// Resolve this config from explicit sources.
    fn from_sources(sources: Sources) -> Result<Self> {
        resolve::<Self>(sources)
    }

    /// Resolve this config from argv and the current process environment.
    #[allow(clippy::should_implement_trait)]
    fn from_iter<I, T>(args: I) -> Result<Self>
    where
        I: IntoIterator<Item = T>,
        T: Into<OsString>,
    {
        Self::from_sources(Sources::from_iter(args))
    }

    /// Resolve this config from the current process.
    fn try_cli() -> Result<Self> {
        Self::from_sources(Sources::new())
    }

    /// Resolve this config from the current process or exit with a user-facing message.
    fn cli() -> Self {
        match Self::try_cli() {
            Ok(cfg) => cfg,
            Err(Error::HelpRequested { text, color }) => {
                if matches!(color, ColorChoice::Auto) {
                    if let Err(err) = print_help_to_stdout(Self::config_spec(), color) {
                        eprintln!("failed to print help: {err}");
                        println!("{text}");
                    }
                } else {
                    println!("{text}");
                }
                std::process::exit(0);
            }
            Err(Error::CompletionRequested(help)) => {
                println!("{help}");
                std::process::exit(0);
            }
            Err(err) => {
                eprintln!("{err}");
                std::process::exit(2);
            }
        }
    }

    /// Render help text for this config.
    fn help() -> String {
        render_help(Self::config_spec())
    }

    /// Render help text with an explicit color policy.
    fn help_with_color(color: ColorChoice) -> String {
        render_help_with_color(Self::config_spec(), color)
    }

    /// Generate a shell completion script for this config.
    fn completion_script(shell: Shell, bin_name: &str) -> String {
        render_completion(Self::config_spec(), shell, bin_name)
    }
}

/// A derived modal config enum.
pub trait ModalConfig: Sized {
    /// Static metadata generated by the derive macro.
    fn modal_spec() -> &'static ModalSpec;

    /// Resolve this modal config from explicit sources.
    fn from_sources(sources: Sources) -> Result<Self>;

    /// Resolve this modal config from argv and the current process environment.
    #[allow(clippy::should_implement_trait)]
    fn from_iter<I, T>(args: I) -> Result<Self>
    where
        I: IntoIterator<Item = T>,
        T: Into<OsString>,
    {
        Self::from_sources(Sources::from_iter(args))
    }

    /// Resolve this modal config from the current process.
    fn try_cli() -> Result<Self> {
        Self::from_sources(Sources::new())
    }

    /// Resolve this modal config from the current process or exit with a user-facing message.
    fn cli() -> Self {
        match Self::try_cli() {
            Ok(cfg) => cfg,
            Err(Error::HelpRequested { text, color }) => {
                if matches!(color, ColorChoice::Auto) {
                    if let Err(err) = print_modal_help_to_stdout(Self::modal_spec(), color) {
                        eprintln!("failed to print help: {err}");
                        println!("{text}");
                    }
                } else {
                    println!("{text}");
                }
                std::process::exit(0);
            }
            Err(Error::CompletionRequested(help)) => {
                println!("{help}");
                std::process::exit(0);
            }
            Err(err) => {
                eprintln!("{err}");
                std::process::exit(2);
            }
        }
    }

    /// Render help text for this modal config.
    fn help() -> String {
        render_modal_help(Self::modal_spec())
    }

    /// Render help text with an explicit color policy.
    fn help_with_color(color: ColorChoice) -> String {
        render_modal_help_with_color(Self::modal_spec(), color)
    }

    /// Generate a shell completion script for this modal config.
    fn completion_script(shell: Shell, bin_name: &str) -> String {
        render_modal_completion(Self::modal_spec(), shell, bin_name)
    }
}

/// Static description of a config struct.
#[derive(Debug)]
pub struct ConfigSpec {
    pub name: &'static str,
    pub about: Option<&'static str>,
    pub fields: &'static [FieldInfo],
}

/// Static description of a config field.
#[derive(Debug, Clone, Copy)]
pub struct FieldInfo {
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub env: Option<&'static str>,
    pub help: Option<&'static str>,
    pub parser: Parser,
    pub choices: &'static [&'static str],
    pub kind: FieldKind,
}

/// The shape of a config field.
#[derive(Debug, Clone, Copy)]
pub enum FieldKind {
    /// A normal leaf value.
    Value,
    /// A nested config object.
    Subconfig(&'static ConfigSpec),
}

/// Static description of a modal enum.
#[derive(Debug)]
pub struct ModalSpec {
    pub name: &'static str,
    pub about: Option<&'static str>,
    pub variants: &'static [ModalVariantInfo],
    pub default_variant: Option<&'static str>,
}

/// Static description of a modal enum variant.
#[derive(Debug, Clone, Copy)]
pub struct ModalVariantInfo {
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub help: Option<&'static str>,
    pub config_spec: &'static ConfigSpec,
}

/// Parser used for string-only sources.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Parser {
    Auto,
    Csv,
    Yaml,
}

impl Parser {
    pub fn name(self) -> &'static str {
        match self {
            Parser::Auto => "auto",
            Parser::Csv => "csv",
            Parser::Yaml => "yaml",
        }
    }
}

/// Explicit config sources.
#[derive(Debug, Clone)]
pub struct Sources {
    pub args: Vec<OsString>,
    pub env: BTreeMap<String, String>,
    pub config_path: Option<PathBuf>,
    pub config_value: Option<Value>,
}

impl Sources {
    /// Current process argv and environment.
    pub fn new() -> Self {
        Self {
            args: env::args_os().collect(),
            env: env::vars().collect(),
            config_path: None,
            config_value: None,
        }
    }

    /// Empty sources for tests and controlled callers.
    pub fn empty() -> Self {
        Self {
            args: Vec::new(),
            env: BTreeMap::new(),
            config_path: None,
            config_value: None,
        }
    }

    /// Sources with explicit argv and the current process environment.
    #[allow(clippy::should_implement_trait)]
    pub fn from_iter<I, T>(args: I) -> Self
    where
        I: IntoIterator<Item = T>,
        T: Into<OsString>,
    {
        Self {
            args: args.into_iter().map(Into::into).collect(),
            env: env::vars().collect(),
            config_path: None,
            config_value: None,
        }
    }

    /// Replace argv.
    pub fn with_args<I, T>(mut self, args: I) -> Self
    where
        I: IntoIterator<Item = T>,
        T: Into<OsString>,
    {
        self.args = args.into_iter().map(Into::into).collect();
        self
    }

    /// Add or replace one env binding.
    pub fn with_env_pair(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.env.insert(key.into(), value.into());
        self
    }

    /// Add or replace many env bindings.
    pub fn with_env<I, K, V>(mut self, pairs: I) -> Self
    where
        I: IntoIterator<Item = (K, V)>,
        K: Into<String>,
        V: Into<String>,
    {
        for (key, value) in pairs {
            self.env.insert(key.into(), value.into());
        }
        self
    }

    /// Set a config file path.
    pub fn with_config_path(mut self, path: impl Into<PathBuf>) -> Self {
        self.config_path = Some(path.into());
        self
    }

    /// Set an already-loaded config value.
    pub fn with_config_value(mut self, value: Value) -> Self {
        self.config_value = Some(value);
        self
    }
}

impl Default for Sources {
    fn default() -> Self {
        Self::new()
    }
}

/// Errors returned by kwconf-rs.
#[derive(Debug)]
pub enum Error {
    HelpRequested { text: String, color: ColorChoice },
    CompletionRequested(String),
    Io {
        path: PathBuf,
        source: std::io::Error,
    },
    UnknownArgument(String),
    UnknownField {
        field: String,
        source: &'static str,
    },
    MissingValue(String),
    InvalidCompletionShell(String),
    InvalidColorChoice(String),
    InvalidModalVariant(String),
    Parse {
        field: String,
        value: String,
        parser: Parser,
        source: &'static str,
        message: String,
    },
    Choice {
        field: String,
        value: String,
        choices: &'static [&'static str],
    },
    Deserialize(String),
    Message(String),
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Error::HelpRequested { text, .. } => write!(f, "{text}"),
            Error::CompletionRequested(help) => write!(f, "{help}"),
            Error::Io { path, source } => write!(f, "failed to read {}: {source}", path.display()),
            Error::UnknownArgument(arg) => write!(f, "unknown argument: {arg}"),
            Error::UnknownField { field, source } => write!(f, "unknown {source} field: {field}"),
            Error::MissingValue(arg) => write!(f, "missing value for {arg}"),
            Error::InvalidCompletionShell(shell) => write!(
                f,
                "invalid completion shell: {shell:?}. Expected one of: bash, elvish, fish, powershell, zsh"
            ),
            Error::InvalidColorChoice(choice) => write!(
                f,
                "invalid color choice: {choice:?}. Expected one of: auto, always, never"
            ),
            Error::InvalidModalVariant(name) => write!(f, "invalid modal variant: {name}"),
            Error::Parse { field, value, parser, source, message } => write!(
                f,
                "failed to parse {source} value for {field} with {} parser: {value:?}: {message}",
                parser.name()
            ),
            Error::Choice { field, value, choices } => {
                write!(f, "invalid value for {field}: {value:?}. Expected one of: {}", choices.join(", "))
            }
            Error::Deserialize(message) => write!(f, "failed to deserialize config: {message}"),
            Error::Message(message) => write!(f, "{message}"),
        }
    }
}

impl std::error::Error for Error {}

fn resolve<T>(sources: Sources) -> Result<T>
where
    T: Config,
{
    let spec = T::config_spec();
    let mut root = default_object::<T>()?;
    let argv = parse_argv(spec, &sources.args)?;

    if argv.help_requested {
        let color = argv.color_choice.unwrap_or(ColorChoice::Auto);
        return Err(Error::HelpRequested {
            text: render_help_with_color(spec, color),
            color,
        });
    }

    if let Some(shell) = argv.completion_shell {
        return Err(Error::CompletionRequested(render_completion(spec, shell, spec.name)));
    }

    if let Some(value) = sources.config_value {
        merge_config_object(spec, &mut root, value, "config value")?;
    } else {
        let config_path = argv.config_path.or(sources.config_path);
        if let Some(path) = config_path {
            let file_value = read_config_file(&path)?;
            merge_config_object(spec, &mut root, file_value, "config file")?;
        }
    }

    apply_env(spec, &mut root, &sources.env)?;

    for (name, value) in argv.values {
        let path = find_field_path(spec, &name).ok_or_else(|| Error::UnknownArgument(format!("--{name}")))?;
        let field = *path.last().expect("field path is non-empty");
        let value = parse_string_value(field, &value, "argv")?;
        apply_choice_path(&path, &value)?;
        set_path_value(&mut root, &path, value)?;
    }

    serde_json::from_value(Value::Object(root)).map_err(|err| Error::Deserialize(err.to_string()))
}

fn default_object<T>() -> Result<Map<String, Value>>
where
    T: Config,
{
    match serde_json::to_value(T::default()).map_err(|err| Error::Deserialize(err.to_string()))? {
        Value::Object(map) => Ok(map),
        _ => Err(Error::Message("config defaults must serialize as an object".to_string())),
    }
}

#[derive(Debug, Default)]
struct ParsedArgv {
    values: BTreeMap<String, String>,
    config_path: Option<PathBuf>,
    completion_shell: Option<Shell>,
    color_choice: Option<ColorChoice>,
    help_requested: bool,
}

fn parse_argv(spec: &ConfigSpec, args: &[OsString]) -> Result<ParsedArgv> {
    let mut parsed = ParsedArgv::default();
    let mut iter = args.iter().skip(1).peekable();

    while let Some(raw) = iter.next() {
        let arg = raw.to_str().ok_or_else(|| Error::Message("argv contains non-UTF-8 text".to_string()))?;

        if arg == "--help" || arg == "-h" {
            parsed.help_requested = true;
            continue;
        }

        if arg == "--" {
            break;
        }

        if !arg.starts_with("--") {
            return Err(Error::UnknownArgument(arg.to_string()));
        }

        let body = &arg[2..];
        let (key, value) = if let Some((key, value)) = body.split_once('=') {
            (key.to_string(), value.to_string())
        } else {
            let key = body.to_string();
            let value = match iter.peek() {
                Some(next) if !next.to_string_lossy().starts_with("--") => {
                    iter.next()
                        .and_then(|v| v.to_str().map(ToOwned::to_owned))
                        .ok_or_else(|| Error::Message("argv contains non-UTF-8 text".to_string()))?
                }
                _ => "true".to_string(),
            };
            (key, value)
        };

        let key = normalize_path(&key);
        if key == "config" {
            if value == "true" {
                return Err(Error::MissingValue("--config".to_string()));
            }
            parsed.config_path = Some(PathBuf::from(value));
            continue;
        }

        if key == "generate_completion" {
            if value == "true" {
                return Err(Error::MissingValue("--generate-completion".to_string()));
            }
            parsed.completion_shell = Some(parse_shell(&value)?);
            continue;
        }

        if key == "color" {
            if value == "true" {
                return Err(Error::MissingValue("--color".to_string()));
            }
            parsed.color_choice = Some(parse_color_choice(&value)?);
            continue;
        }

        if find_field_path(spec, &key).is_none() {
            return Err(Error::UnknownArgument(format!("--{key}")));
        }
        parsed.values.insert(key, value);
    }

    Ok(parsed)
}

fn merge_config_object(
    spec: &ConfigSpec,
    root: &mut Map<String, Value>,
    value: Value,
    source: &'static str,
) -> Result<()> {
    let Value::Object(map) = value else {
        return Err(Error::Message(format!("{source} must contain an object at the top level")));
    };

    for (key, value) in map {
        let key = normalize_path(&key);
        if key.contains('.') {
            let path = find_field_path(spec, &key).ok_or_else(|| Error::UnknownField {
                field: key.clone(),
                source,
            })?;
            apply_choice_path(&path, &value)?;
            set_path_value(root, &path, value)?;
            continue;
        }

        let field = find_field(spec, &key).ok_or_else(|| Error::UnknownField {
            field: key.clone(),
            source,
        })?;

        match field.kind {
            FieldKind::Value => {
                apply_choice(field, &value)?;
                root.insert(field.name.to_string(), value);
            }
            FieldKind::Subconfig(child_spec) => {
                let Value::Object(_) = value else {
                    return Err(Error::Message(format!("{source} field {} must contain an object", field.name)));
                };
                let child = ensure_child_object(root, field.name)?;
                merge_config_object(child_spec, child, value, source)?;
            }
        }
    }
    Ok(())
}

fn apply_env(spec: &ConfigSpec, root: &mut Map<String, Value>, env: &BTreeMap<String, String>) -> Result<()> {
    let mut paths = Vec::new();
    collect_field_paths(spec, Vec::new(), &mut paths);
    for path in paths {
        let field = *path.last().expect("field path is non-empty");
        if let Some(env_name) = field.env {
            if let Some(text) = env.get(env_name) {
                let value = parse_string_value(field, text, "env")?;
                apply_choice_path(&path, &value)?;
                set_path_value(root, &path, value)?;
            }
        }
    }
    Ok(())
}

fn collect_field_paths<'a>(spec: &'a ConfigSpec, prefix: Vec<&'a FieldInfo>, out: &mut Vec<Vec<&'a FieldInfo>>) {
    for field in spec.fields {
        let mut path = prefix.clone();
        path.push(field);
        match field.kind {
            FieldKind::Value => out.push(path),
            FieldKind::Subconfig(child_spec) => collect_field_paths(child_spec, path, out),
        }
    }
}

fn set_path_value(root: &mut Map<String, Value>, path: &[&FieldInfo], value: Value) -> Result<()> {
    if path.is_empty() {
        return Err(Error::Message("empty field path".to_string()));
    }
    if path.len() == 1 {
        root.insert(path[0].name.to_string(), value);
        return Ok(());
    }
    let child = ensure_child_object(root, path[0].name)?;
    set_path_value(child, &path[1..], value)
}

fn ensure_child_object<'a>(root: &'a mut Map<String, Value>, name: &str) -> Result<&'a mut Map<String, Value>> {
    let value = root
        .entry(name.to_string())
        .or_insert_with(|| Value::Object(Map::new()));
    match value {
        Value::Object(map) => Ok(map),
        _ => Err(Error::Message(format!("field {name} must contain an object"))),
    }
}

fn apply_choice_path(path: &[&FieldInfo], value: &Value) -> Result<()> {
    let field = *path.last().expect("field path is non-empty");
    apply_choice(field, value)
}

fn find_field_path<'a>(spec: &'a ConfigSpec, key: &str) -> Option<Vec<&'a FieldInfo>> {
    let mut spec = spec;
    let parts: Vec<String> = normalize_path(key).split('.').map(ToOwned::to_owned).collect();
    let mut path = Vec::new();
    for (index, part) in parts.iter().enumerate() {
        let field = find_field(spec, part)?;
        path.push(field);
        if index + 1 < parts.len() {
            match field.kind {
                FieldKind::Subconfig(child_spec) => spec = child_spec,
                FieldKind::Value => return None,
            }
        }
    }
    Some(path)
}

fn find_field<'a>(spec: &'a ConfigSpec, key: &str) -> Option<&'a FieldInfo> {
    let key = normalize_key(key);
    spec.fields.iter().find(|field| {
        normalize_key(field.name) == key || field.aliases.iter().any(|alias| normalize_key(alias) == key)
    })
}

fn normalize_path(key: &str) -> String {
    key.trim_start_matches('-')
        .split('.')
        .map(normalize_key)
        .collect::<Vec<_>>()
        .join(".")
}

fn normalize_key(key: &str) -> String {
    key.trim_start_matches('-').replace('-', "_")
}

fn read_config_file(path: &Path) -> Result<Value> {
    let text = std::fs::read_to_string(path).map_err(|source| Error::Io {
        path: path.to_path_buf(),
        source,
    })?;

    let ext = path.extension().and_then(|s| s.to_str()).unwrap_or_default().to_ascii_lowercase();
    match ext.as_str() {
        "toml" => parse_toml_file(&text),
        "json" => serde_json::from_str(&text).map_err(|err| Error::Deserialize(err.to_string())),
        "yaml" | "yml" => yaml_serde::from_str(&text).map_err(|err| Error::Deserialize(err.to_string())),
        _ => parse_toml_file(&text)
            .or_else(|_| serde_json::from_str(&text).map_err(|err| Error::Deserialize(err.to_string())))
            .or_else(|_| yaml_serde::from_str(&text).map_err(|err| Error::Deserialize(err.to_string()))),
    }
}

fn parse_toml_file(text: &str) -> Result<Value> {
    let value: toml::Value = toml::from_str(text).map_err(|err| Error::Deserialize(err.to_string()))?;
    serde_json::to_value(value).map_err(|err| Error::Deserialize(err.to_string()))
}

fn parse_string_value(field: &FieldInfo, text: &str, source: &'static str) -> Result<Value> {
    match field.parser {
        Parser::Auto => parse_auto(text).map_err(|message| Error::Parse {
            field: field.name.to_string(),
            value: text.to_string(),
            parser: field.parser,
            source,
            message,
        }),
        Parser::Csv => Ok(parse_csv(text)),
        Parser::Yaml => yaml_serde::from_str(text).map_err(|err| Error::Parse {
            field: field.name.to_string(),
            value: text.to_string(),
            parser: field.parser,
            source,
            message: err.to_string(),
        }),
    }
}

fn parse_auto(text: &str) -> std::result::Result<Value, String> {
    let trimmed = text.trim();
    if trimmed.eq_ignore_ascii_case("true") {
        return Ok(Value::Bool(true));
    }
    if trimmed.eq_ignore_ascii_case("false") {
        return Ok(Value::Bool(false));
    }
    if trimmed.eq_ignore_ascii_case("null") || trimmed.eq_ignore_ascii_case("none") {
        return Ok(Value::Null);
    }
    if trimmed.starts_with('[') || trimmed.starts_with('{') {
        return serde_json::from_str(trimmed).map_err(|err| err.to_string());
    }
    if let Ok(value) = trimmed.parse::<i64>() {
        return Ok(Value::Number(value.into()));
    }
    if (trimmed.contains('.') || trimmed.contains('e') || trimmed.contains('E')) && trimmed.parse::<f64>().is_ok() {
        let value = trimmed.parse::<f64>().map_err(|err| err.to_string())?;
        if let Some(number) = serde_json::Number::from_f64(value) {
            return Ok(Value::Number(number));
        }
    }
    Ok(Value::String(text.to_string()))
}

fn parse_csv(text: &str) -> Value {
    if text.trim().is_empty() {
        return Value::Array(Vec::new());
    }
    Value::Array(
        text.split(',')
            .map(|part| Value::String(part.trim().to_string()))
            .collect(),
    )
}

fn parse_color_choice(text: &str) -> Result<ColorChoice> {
    match text.to_ascii_lowercase().as_str() {
        "auto" => Ok(ColorChoice::Auto),
        "always" => Ok(ColorChoice::Always),
        "never" => Ok(ColorChoice::Never),
        _ => Err(Error::InvalidColorChoice(text.to_string())),
    }
}

fn parse_shell(text: &str) -> Result<Shell> {
    match text.to_ascii_lowercase().as_str() {
        "bash" => Ok(Shell::Bash),
        "elvish" => Ok(Shell::Elvish),
        "fish" => Ok(Shell::Fish),
        "powershell" | "power-shell" | "pwsh" => Ok(Shell::PowerShell),
        "zsh" => Ok(Shell::Zsh),
        _ => Err(Error::InvalidCompletionShell(text.to_string())),
    }
}

fn apply_choice(field: &FieldInfo, value: &Value) -> Result<()> {
    if field.choices.is_empty() {
        return Ok(());
    }
    let Some(text) = value.as_str() else {
        return Ok(());
    };
    if field.choices.iter().any(|choice| *choice == text) {
        Ok(())
    } else {
        Err(Error::Choice {
            field: field.name.to_string(),
            value: text.to_string(),
            choices: field.choices,
        })
    }
}

fn render_help(spec: &ConfigSpec) -> String {
    render_help_with_color(spec, ColorChoice::Auto)
}

fn render_help_with_color(spec: &ConfigSpec, color: ColorChoice) -> String {
    let mut cmd = build_command(spec, color);
    let help = cmd.render_help();
    if matches!(color, ColorChoice::Always) {
        help.ansi().to_string()
    } else {
        help.to_string()
    }
}

fn print_help_to_stdout(spec: &ConfigSpec, color: ColorChoice) -> std::io::Result<()> {
    let mut cmd = build_command(spec, color);
    cmd.print_help()?;
    println!();
    Ok(())
}

fn render_completion(spec: &ConfigSpec, shell: Shell, bin_name: &str) -> String {
    let mut cmd = build_command(spec, ColorChoice::Never);
    cmd.set_bin_name(bin_name.to_string());
    let mut buf = Vec::new();
    generate(shell, &mut cmd, bin_name.to_string(), &mut buf);
    String::from_utf8(buf).expect("clap completion output is UTF-8")
}

fn kwconf_help_styles() -> Styles {
    Styles::styled()
        .header(AnsiColor::Green.on_default().effects(Effects::BOLD))
        .usage(AnsiColor::Green.on_default().effects(Effects::BOLD))
        .literal(AnsiColor::Cyan.on_default().effects(Effects::BOLD))
        .placeholder(AnsiColor::Cyan.on_default())
        .error(AnsiColor::Red.on_default().effects(Effects::BOLD))
        .valid(AnsiColor::Cyan.on_default().effects(Effects::BOLD))
        .invalid(AnsiColor::Yellow.on_default().effects(Effects::BOLD))
}

fn build_command(spec: &ConfigSpec, color: ColorChoice) -> Command {
    build_command_with_name(spec, spec.name, color)
}

fn build_command_with_name(spec: &ConfigSpec, name: &str, color: ColorChoice) -> Command {
    let mut cmd = Command::new(name.to_string())
        .styles(kwconf_help_styles())
        .color(color)
        .arg_required_else_help(false)
        .arg(
            Arg::new("config")
                .long("config")
                .value_name("PATH")
                .help("Read TOML, JSON, YAML, or YML config."),
        )
        .arg(
            Arg::new("generate-completion")
                .long("generate-completion")
                .value_name("SHELL")
                .value_parser(clap::value_parser!(Shell))
                .help("Generate a shell completion script."),
        )
        .arg(
            Arg::new("color")
                .long("color")
                .value_name("WHEN")
                .value_parser(["auto", "always", "never"])
                .help("Control help color: auto, always, or never."),
        );

    if let Some(about) = spec.about {
        cmd = cmd.about(about);
    }

    let mut paths = Vec::new();
    collect_named_field_paths(spec, Vec::new(), &mut paths);
    for (path_name, field) in paths {
        let mut arg = Arg::new(path_name.clone())
            .long(path_name.replace('_', "-"))
            .value_name("VALUE")
            .action(ArgAction::Set)
            .help(field_help(field));

        for alias in field.aliases {
            let alias_path = replace_leaf_name(&path_name, alias);
            arg = arg.visible_alias(alias_path.replace('_', "-"));
        }

        if !field.choices.is_empty() {
            arg = arg.value_parser(clap::builder::PossibleValuesParser::new(field.choices.iter().copied()));
        }

        cmd = cmd.arg(arg);
    }

    cmd
}

fn collect_named_field_paths<'a>(spec: &'a ConfigSpec, prefix: Vec<String>, out: &mut Vec<(String, &'a FieldInfo)>) {
    for field in spec.fields {
        let mut path = prefix.clone();
        path.push(field.name.to_string());
        match field.kind {
            FieldKind::Value => out.push((path.join("."), field)),
            FieldKind::Subconfig(child_spec) => collect_named_field_paths(child_spec, path, out),
        }
    }
}

fn replace_leaf_name(path: &str, leaf: &str) -> String {
    if let Some((head, _)) = path.rsplit_once('.') {
        format!("{head}.{leaf}")
    } else {
        leaf.to_string()
    }
}

fn field_help(field: &FieldInfo) -> String {
    let mut parts = Vec::new();
    if let Some(help) = field.help {
        parts.push(help.to_string());
    }
    if field.parser != Parser::Auto {
        parts.push(format!("parser={}", field.parser.name()));
    }
    if let Some(env) = field.env {
        parts.push(format!("env={env}"));
    }
    if !field.choices.is_empty() {
        parts.push(format!("choices={}", field.choices.join("|")));
    }
    parts.join(" ")
}

/// Resolved modal selection used by derive-generated code.
#[doc(hidden)]
pub struct ModalSelection {
    pub variant: &'static str,
    pub sources: Sources,
}

/// Resolve modal sources into one variant and child sources.
#[doc(hidden)]
pub fn resolve_modal_selection(spec: &'static ModalSpec, sources: Sources) -> Result<ModalSelection> {
    let parsed = parse_modal_argv(spec, &sources.args)?;

    if parsed.help_requested {
        let color = parsed.color_choice.unwrap_or(ColorChoice::Auto);
        return Err(Error::HelpRequested {
            text: render_modal_help_with_color(spec, color),
            color,
        });
    }

    if let Some(shell) = parsed.completion_shell {
        return Err(Error::CompletionRequested(render_modal_completion(spec, shell, spec.name)));
    }

    let config_path = parsed.config_path.clone().or_else(|| sources.config_path.clone());
    let config_value = if let Some(value) = sources.config_value.clone() {
        Some(value)
    } else if let Some(path) = config_path.as_ref() {
        Some(read_config_file(path)?)
    } else {
        None
    };

    let variant_name = if let Some(name) = parsed.variant_name.as_deref() {
        canonical_modal_variant(spec, name)?.name
    } else if let Some(name) = modal_variant_from_config(&config_value) {
        canonical_modal_variant(spec, &name)?.name
    } else if let Some(name) = spec.default_variant {
        canonical_modal_variant(spec, name)?.name
    } else {
        spec.variants
            .first()
            .map(|variant| variant.name)
            .ok_or_else(|| Error::Message("modal config has no variants".to_string()))?
    };

    let mut child_sources = sources.clone();
    child_sources.args = parsed.child_args.unwrap_or_else(|| vec![OsString::from(variant_name)]);
    child_sources.config_path = None;
    child_sources.config_value = config_value.and_then(|value| modal_child_config_value(spec, variant_name, value));

    Ok(ModalSelection {
        variant: variant_name,
        sources: child_sources,
    })
}

#[derive(Debug, Default)]
struct ParsedModalArgv {
    variant_name: Option<String>,
    child_args: Option<Vec<OsString>>,
    config_path: Option<PathBuf>,
    completion_shell: Option<Shell>,
    color_choice: Option<ColorChoice>,
    help_requested: bool,
}

fn parse_modal_argv(spec: &ModalSpec, args: &[OsString]) -> Result<ParsedModalArgv> {
    let mut parsed = ParsedModalArgv::default();
    let program = args
        .first()
        .cloned()
        .unwrap_or_else(|| OsString::from(spec.name));
    let mut iter = args.iter().skip(1).peekable();

    while let Some(raw) = iter.next() {
        let arg = raw.to_str().ok_or_else(|| Error::Message("argv contains non-UTF-8 text".to_string()))?;

        if arg == "--help" || arg == "-h" {
            parsed.help_requested = true;
            continue;
        }

        if arg == "--" {
            break;
        }

        if arg.starts_with("--") {
            let body = &arg[2..];
            let (key, value) = if let Some((key, value)) = body.split_once('=') {
                (key.to_string(), value.to_string())
            } else {
                let key = body.to_string();
                let value = match iter.peek() {
                    Some(next) if !next.to_string_lossy().starts_with("--") => {
                        iter.next()
                            .and_then(|v| v.to_str().map(ToOwned::to_owned))
                            .ok_or_else(|| Error::Message("argv contains non-UTF-8 text".to_string()))?
                    }
                    _ => "true".to_string(),
                };
                (key, value)
            };
            let key = normalize_key(&key);
            if key == "config" {
                if value == "true" {
                    return Err(Error::MissingValue("--config".to_string()));
                }
                parsed.config_path = Some(PathBuf::from(value));
                continue;
            }
            if key == "generate_completion" {
                if value == "true" {
                    return Err(Error::MissingValue("--generate-completion".to_string()));
                }
                parsed.completion_shell = Some(parse_shell(&value)?);
                continue;
            }
            if key == "color" {
                if value == "true" {
                    return Err(Error::MissingValue("--color".to_string()));
                }
                parsed.color_choice = Some(parse_color_choice(&value)?);
                continue;
            }
            return Err(Error::UnknownArgument(format!("--{key}")));
        }

        let variant = canonical_modal_variant(spec, arg)?.name.to_string();
        let mut child_args = Vec::new();
        child_args.push(OsString::from(format!("{} {}", program.to_string_lossy(), variant)));
        for item in iter {
            child_args.push(item.clone());
        }
        parsed.variant_name = Some(variant);
        parsed.child_args = Some(child_args);
        return Ok(parsed);
    }

    Ok(parsed)
}

fn canonical_modal_variant<'a>(spec: &'a ModalSpec, name: &str) -> Result<&'a ModalVariantInfo> {
    let key = normalize_key(name);
    spec.variants
        .iter()
        .find(|variant| {
            normalize_key(variant.name) == key || variant.aliases.iter().any(|alias| normalize_key(alias) == key)
        })
        .ok_or_else(|| Error::InvalidModalVariant(name.to_string()))
}

fn modal_variant_from_config(config_value: &Option<Value>) -> Option<String> {
    let Some(Value::Object(map)) = config_value else {
        return None;
    };
    map.get("command")
        .or_else(|| map.get("mode"))
        .and_then(Value::as_str)
        .map(ToOwned::to_owned)
}

fn modal_child_config_value(spec: &ModalSpec, variant_name: &str, value: Value) -> Option<Value> {
    let Value::Object(mut map) = value else {
        return None;
    };

    if let Some(value) = map.remove(variant_name) {
        return Some(value);
    }

    for variant in spec.variants {
        if let Some(value) = map.remove(variant.name) {
            if normalize_key(variant.name) == normalize_key(variant_name) {
                return Some(value);
            }
        }
        for alias in variant.aliases {
            if let Some(value) = map.remove(*alias) {
                if normalize_key(alias) == normalize_key(variant_name) {
                    return Some(value);
                }
            }
        }
    }

    map.remove("command");
    map.remove("mode");
    for variant in spec.variants {
        map.remove(variant.name);
        for alias in variant.aliases {
            map.remove(*alias);
        }
    }

    if map.is_empty() {
        None
    } else {
        Some(Value::Object(map))
    }
}

fn render_modal_help(spec: &ModalSpec) -> String {
    render_modal_help_with_color(spec, ColorChoice::Auto)
}

fn render_modal_help_with_color(spec: &ModalSpec, color: ColorChoice) -> String {
    let mut cmd = build_modal_command(spec, color);
    let help = cmd.render_help();
    if matches!(color, ColorChoice::Always) {
        help.ansi().to_string()
    } else {
        help.to_string()
    }
}

fn print_modal_help_to_stdout(spec: &ModalSpec, color: ColorChoice) -> std::io::Result<()> {
    let mut cmd = build_modal_command(spec, color);
    cmd.print_help()?;
    println!();
    Ok(())
}

fn render_modal_completion(spec: &ModalSpec, shell: Shell, bin_name: &str) -> String {
    let mut cmd = build_modal_command(spec, ColorChoice::Never);
    cmd.set_bin_name(bin_name.to_string());
    let mut buf = Vec::new();
    generate(shell, &mut cmd, bin_name.to_string(), &mut buf);
    String::from_utf8(buf).expect("clap completion output is UTF-8")
}

fn build_modal_command(spec: &ModalSpec, color: ColorChoice) -> Command {
    let mut cmd = Command::new(spec.name)
        .styles(kwconf_help_styles())
        .color(color)
        .arg_required_else_help(false)
        .subcommand_required(false)
        .arg(
            Arg::new("config")
                .long("config")
                .value_name("PATH")
                .help("Read TOML, JSON, YAML, or YML config."),
        )
        .arg(
            Arg::new("generate-completion")
                .long("generate-completion")
                .value_name("SHELL")
                .value_parser(clap::value_parser!(Shell))
                .help("Generate a shell completion script."),
        )
        .arg(
            Arg::new("color")
                .long("color")
                .value_name("WHEN")
                .value_parser(["auto", "always", "never"])
                .help("Control help color: auto, always, or never."),
        );

    if let Some(about) = spec.about {
        cmd = cmd.about(about);
    }

    for variant in spec.variants {
        let mut sub = build_command_with_name(variant.config_spec, variant.name, color);
        if let Some(help) = variant.help {
            sub = sub.about(help);
        }
        for alias in variant.aliases {
            sub = sub.visible_alias(alias.replace('_', "-"));
        }
        cmd = cmd.subcommand(sub);
    }

    cmd
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn auto_parser_handles_basic_scalars() {
        assert_eq!(parse_auto("true").unwrap(), Value::Bool(true));
        assert_eq!(parse_auto("3").unwrap(), Value::Number(3.into()));
        assert_eq!(parse_auto("word").unwrap(), Value::String("word".to_string()));
    }

    #[test]
    fn csv_parser_trims_parts() {
        assert_eq!(
            parse_csv("a, b,c"),
            Value::Array(vec![
                Value::String("a".to_string()),
                Value::String("b".to_string()),
                Value::String("c".to_string()),
            ])
        );
    }

    #[test]
    fn shell_parser_accepts_common_names() {
        assert_eq!(parse_shell("bash").unwrap(), Shell::Bash);
        assert_eq!(parse_shell("pwsh").unwrap(), Shell::PowerShell);
    }

    #[test]
    fn color_parser_accepts_common_names() {
        assert!(matches!(parse_color_choice("auto").unwrap(), ColorChoice::Auto));
        assert!(matches!(parse_color_choice("always").unwrap(), ColorChoice::Always));
        assert!(matches!(parse_color_choice("never").unwrap(), ColorChoice::Never));
    }
}
