//! kwconf-style CLI and config resolution for Rust.
//!
//! The runtime keeps one small contract:
//!
//! ```text
//! defaults < config file < env < argv
//! ```
//!
//! Parsers apply to string-only sources: argv and env.

use clap::{Arg, ArgAction, Command};
use clap::builder::styling::{AnsiColor, Effects, Styles};
use clap_complete::aot::{generate, Shell};
use serde::de::DeserializeOwned;
use serde::Serialize;
use serde_json::{Map, Value};
use std::collections::BTreeMap;
use std::env;
use std::ffi::OsString;
use std::fmt;
use std::path::{Path, PathBuf};

pub use kwconf_derive::Config;
pub use clap::ColorChoice;
pub use clap::ColorChoice as HelpColorChoice;
pub use clap_complete::aot::Shell as CompletionShell;

/// Result type used by kwconf-rs.
pub type Result<T> = std::result::Result<T, Error>;

/// A derived config object.
pub trait Config: Default + Serialize + DeserializeOwned + Sized {
    /// Static metadata generated by the derive macro.
    fn config_spec() -> &'static ConfigSpec;

    /// Resolve this config from explicit sources.
    fn from_sources(sources: Sources) -> Result<Self> {
        resolve::<Self>(sources)
    }

    /// Resolve this config from argv and the current process environment.
    #[allow(clippy::should_implement_trait)]
    fn from_iter<I, T>(args: I) -> Result<Self>
    where
        I: IntoIterator<Item = T>,
        T: Into<OsString>,
    {
        Self::from_sources(Sources::from_iter(args))
    }

    /// Resolve this config from the current process.
    fn try_cli() -> Result<Self> {
        Self::from_sources(Sources::new())
    }

    /// Resolve this config from the current process or exit with a user-facing message.
    fn cli() -> Self {
        match Self::try_cli() {
            Ok(cfg) => cfg,
            Err(Error::HelpRequested { text, color }) => {
                if matches!(color, ColorChoice::Auto) {
                    if let Err(err) = print_help_to_stdout(Self::config_spec(), color) {
                        eprintln!("failed to print help: {err}");
                        println!("{text}");
                    }
                } else {
                    println!("{text}");
                }
                std::process::exit(0);
            }
            Err(Error::CompletionRequested(help)) => {
                println!("{help}");
                std::process::exit(0);
            }
            Err(err) => {
                eprintln!("{err}");
                std::process::exit(2);
            }
        }
    }

    /// Render help text for this config.
    fn help() -> String {
        render_help(Self::config_spec())
    }

    /// Render help text with an explicit color policy.
    fn help_with_color(color: ColorChoice) -> String {
        render_help_with_color(Self::config_spec(), color)
    }

    /// Generate a shell completion script for this config.
    fn completion_script(shell: Shell, bin_name: &str) -> String {
        render_completion(Self::config_spec(), shell, bin_name)
    }
}

/// Static description of a config struct.
#[derive(Debug)]
pub struct ConfigSpec {
    pub name: &'static str,
    pub about: Option<&'static str>,
    pub fields: &'static [FieldInfo],
}

/// Static description of a config field.
#[derive(Debug, Clone, Copy)]
pub struct FieldInfo {
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub env: Option<&'static str>,
    pub help: Option<&'static str>,
    pub parser: Parser,
    pub choices: &'static [&'static str],
}

/// Parser used for string-only sources.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Parser {
    Auto,
    Csv,
    Yaml,
}

impl Parser {
    pub fn name(self) -> &'static str {
        match self {
            Parser::Auto => "auto",
            Parser::Csv => "csv",
            Parser::Yaml => "yaml",
        }
    }
}

/// Explicit config sources.
#[derive(Debug, Clone)]
pub struct Sources {
    pub args: Vec<OsString>,
    pub env: BTreeMap<String, String>,
    pub config_path: Option<PathBuf>,
}

impl Sources {
    /// Current process argv and environment.
    pub fn new() -> Self {
        Self {
            args: env::args_os().collect(),
            env: env::vars().collect(),
            config_path: None,
        }
    }

    /// Empty sources for tests and controlled callers.
    pub fn empty() -> Self {
        Self {
            args: Vec::new(),
            env: BTreeMap::new(),
            config_path: None,
        }
    }

    /// Sources with explicit argv and the current process environment.
    #[allow(clippy::should_implement_trait)]
    pub fn from_iter<I, T>(args: I) -> Self
    where
        I: IntoIterator<Item = T>,
        T: Into<OsString>,
    {
        Self {
            args: args.into_iter().map(Into::into).collect(),
            env: env::vars().collect(),
            config_path: None,
        }
    }

    /// Replace argv.
    pub fn with_args<I, T>(mut self, args: I) -> Self
    where
        I: IntoIterator<Item = T>,
        T: Into<OsString>,
    {
        self.args = args.into_iter().map(Into::into).collect();
        self
    }

    /// Add or replace one env binding.
    pub fn with_env_pair(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.env.insert(key.into(), value.into());
        self
    }

    /// Add or replace many env bindings.
    pub fn with_env<I, K, V>(mut self, pairs: I) -> Self
    where
        I: IntoIterator<Item = (K, V)>,
        K: Into<String>,
        V: Into<String>,
    {
        for (key, value) in pairs {
            self.env.insert(key.into(), value.into());
        }
        self
    }

    /// Set a config file path.
    pub fn with_config_path(mut self, path: impl Into<PathBuf>) -> Self {
        self.config_path = Some(path.into());
        self
    }
}

impl Default for Sources {
    fn default() -> Self {
        Self::new()
    }
}

/// Errors returned by kwconf-rs.
#[derive(Debug)]
pub enum Error {
    HelpRequested { text: String, color: ColorChoice },
    CompletionRequested(String),
    Io {
        path: PathBuf,
        source: std::io::Error,
    },
    UnknownArgument(String),
    UnknownField {
        field: String,
        source: &'static str,
    },
    MissingValue(String),
    InvalidCompletionShell(String),
    InvalidColorChoice(String),
    Parse {
        field: String,
        value: String,
        parser: Parser,
        source: &'static str,
        message: String,
    },
    Choice {
        field: String,
        value: String,
        choices: &'static [&'static str],
    },
    Deserialize(String),
    Message(String),
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Error::HelpRequested { text, .. } => write!(f, "{text}"),
            Error::CompletionRequested(help) => write!(f, "{help}"),
            Error::Io { path, source } => write!(f, "failed to read {}: {source}", path.display()),
            Error::UnknownArgument(arg) => write!(f, "unknown argument: {arg}"),
            Error::UnknownField { field, source } => write!(f, "unknown {source} field: {field}"),
            Error::MissingValue(arg) => write!(f, "missing value for {arg}"),
            Error::InvalidCompletionShell(shell) => write!(
                f,
                "invalid completion shell: {shell:?}. Expected one of: bash, elvish, fish, powershell, zsh"
            ),
            Error::InvalidColorChoice(choice) => write!(
                f,
                "invalid color choice: {choice:?}. Expected one of: auto, always, never"
            ),
            Error::Parse { field, value, parser, source, message } => write!(
                f,
                "failed to parse {source} value for {field} with {} parser: {value:?}: {message}",
                parser.name()
            ),
            Error::Choice { field, value, choices } => {
                write!(f, "invalid value for {field}: {value:?}. Expected one of: {}", choices.join(", "))
            }
            Error::Deserialize(message) => write!(f, "failed to deserialize config: {message}"),
            Error::Message(message) => write!(f, "{message}"),
        }
    }
}

impl std::error::Error for Error {}

fn resolve<T>(sources: Sources) -> Result<T>
where
    T: Config,
{
    let spec = T::config_spec();
    let mut root = default_object::<T>()?;
    let argv = parse_argv(spec, &sources.args)?;

    if argv.help_requested {
        let color = argv.color_choice.unwrap_or(ColorChoice::Auto);
        return Err(Error::HelpRequested {
            text: render_help_with_color(spec, color),
            color,
        });
    }

    if let Some(shell) = argv.completion_shell {
        return Err(Error::CompletionRequested(render_completion(spec, shell, spec.name)));
    }

    let config_path = argv.config_path.or(sources.config_path);
    if let Some(path) = config_path {
        let file_value = read_config_file(&path)?;
        merge_config_object(spec, &mut root, file_value, "config file")?;
    }

    for field in spec.fields {
        if let Some(env_name) = field.env {
            if let Some(text) = sources.env.get(env_name) {
                let value = parse_string_value(field, text, "env")?;
                apply_choice(field, &value)?;
                root.insert(field.name.to_string(), value);
            }
        }
    }

    for (name, value) in argv.values {
        let field = find_field(spec, &name).ok_or_else(|| Error::UnknownArgument(format!("--{name}")))?;
        let value = parse_string_value(field, &value, "argv")?;
        apply_choice(field, &value)?;
        root.insert(field.name.to_string(), value);
    }

    serde_json::from_value(Value::Object(root)).map_err(|err| Error::Deserialize(err.to_string()))
}

fn default_object<T>() -> Result<Map<String, Value>>
where
    T: Config,
{
    match serde_json::to_value(T::default()).map_err(|err| Error::Deserialize(err.to_string()))? {
        Value::Object(map) => Ok(map),
        _ => Err(Error::Message("config defaults must serialize as an object".to_string())),
    }
}

#[derive(Debug, Default)]
struct ParsedArgv {
    values: BTreeMap<String, String>,
    config_path: Option<PathBuf>,
    completion_shell: Option<Shell>,
    color_choice: Option<ColorChoice>,
    help_requested: bool,
}

fn parse_argv(spec: &ConfigSpec, args: &[OsString]) -> Result<ParsedArgv> {
    let mut parsed = ParsedArgv::default();
    let mut iter = args.iter().skip(1).peekable();

    while let Some(raw) = iter.next() {
        let arg = raw.to_str().ok_or_else(|| Error::Message("argv contains non-UTF-8 text".to_string()))?;

        if arg == "--help" || arg == "-h" {
            parsed.help_requested = true;
            continue;
        }

        if arg == "--" {
            break;
        }

        if !arg.starts_with("--") {
            return Err(Error::UnknownArgument(arg.to_string()));
        }

        let body = &arg[2..];
        let (key, value) = if let Some((key, value)) = body.split_once('=') {
            (key.to_string(), value.to_string())
        } else {
            let key = body.to_string();
            let value = match iter.peek() {
                Some(next) if !next.to_string_lossy().starts_with("--") => {
                    iter.next()
                        .and_then(|v| v.to_str().map(ToOwned::to_owned))
                        .ok_or_else(|| Error::Message("argv contains non-UTF-8 text".to_string()))?
                }
                _ => "true".to_string(),
            };
            (key, value)
        };

        let key = normalize_key(&key);
        if key == "config" {
            if value == "true" {
                return Err(Error::MissingValue("--config".to_string()));
            }
            parsed.config_path = Some(PathBuf::from(value));
            continue;
        }

        if key == "generate_completion" {
            if value == "true" {
                return Err(Error::MissingValue("--generate-completion".to_string()));
            }
            parsed.completion_shell = Some(parse_shell(&value)?);
            continue;
        }

        if key == "color" {
            if value == "true" {
                return Err(Error::MissingValue("--color".to_string()));
            }
            parsed.color_choice = Some(parse_color_choice(&value)?);
            continue;
        }

        if find_field(spec, &key).is_none() {
            return Err(Error::UnknownArgument(format!("--{key}")));
        }
        parsed.values.insert(key, value);
    }

    Ok(parsed)
}

fn merge_config_object(
    spec: &ConfigSpec,
    root: &mut Map<String, Value>,
    value: Value,
    source: &'static str,
) -> Result<()> {
    let Value::Object(map) = value else {
        return Err(Error::Message(format!("{source} must contain an object at the top level")));
    };

    for (key, value) in map {
        let key = normalize_key(&key);
        let field = find_field(spec, &key).ok_or_else(|| Error::UnknownField {
            field: key.clone(),
            source,
        })?;
        apply_choice(field, &value)?;
        root.insert(field.name.to_string(), value);
    }
    Ok(())
}

fn find_field<'a>(spec: &'a ConfigSpec, key: &str) -> Option<&'a FieldInfo> {
    let key = normalize_key(key);
    spec.fields.iter().find(|field| {
        normalize_key(field.name) == key || field.aliases.iter().any(|alias| normalize_key(alias) == key)
    })
}

fn normalize_key(key: &str) -> String {
    key.trim_start_matches('-').replace('-', "_")
}

fn read_config_file(path: &Path) -> Result<Value> {
    let text = std::fs::read_to_string(path).map_err(|source| Error::Io {
        path: path.to_path_buf(),
        source,
    })?;

    let ext = path.extension().and_then(|s| s.to_str()).unwrap_or_default().to_ascii_lowercase();
    match ext.as_str() {
        "toml" => parse_toml_file(&text),
        "json" => serde_json::from_str(&text).map_err(|err| Error::Deserialize(err.to_string())),
        "yaml" | "yml" => yaml_serde::from_str(&text).map_err(|err| Error::Deserialize(err.to_string())),
        _ => parse_toml_file(&text)
            .or_else(|_| serde_json::from_str(&text).map_err(|err| Error::Deserialize(err.to_string())))
            .or_else(|_| yaml_serde::from_str(&text).map_err(|err| Error::Deserialize(err.to_string()))),
    }
}

fn parse_toml_file(text: &str) -> Result<Value> {
    let value: toml::Value = toml::from_str(text).map_err(|err| Error::Deserialize(err.to_string()))?;
    serde_json::to_value(value).map_err(|err| Error::Deserialize(err.to_string()))
}

fn parse_string_value(field: &FieldInfo, text: &str, source: &'static str) -> Result<Value> {
    match field.parser {
        Parser::Auto => parse_auto(text).map_err(|message| Error::Parse {
            field: field.name.to_string(),
            value: text.to_string(),
            parser: field.parser,
            source,
            message,
        }),
        Parser::Csv => Ok(parse_csv(text)),
        Parser::Yaml => yaml_serde::from_str(text).map_err(|err| Error::Parse {
            field: field.name.to_string(),
            value: text.to_string(),
            parser: field.parser,
            source,
            message: err.to_string(),
        }),
    }
}

fn parse_auto(text: &str) -> std::result::Result<Value, String> {
    let trimmed = text.trim();
    if trimmed.eq_ignore_ascii_case("true") {
        return Ok(Value::Bool(true));
    }
    if trimmed.eq_ignore_ascii_case("false") {
        return Ok(Value::Bool(false));
    }
    if trimmed.eq_ignore_ascii_case("null") || trimmed.eq_ignore_ascii_case("none") {
        return Ok(Value::Null);
    }
    if trimmed.starts_with('[') || trimmed.starts_with('{') {
        return serde_json::from_str(trimmed).map_err(|err| err.to_string());
    }
    if let Ok(value) = trimmed.parse::<i64>() {
        return Ok(Value::Number(value.into()));
    }
    if (trimmed.contains('.') || trimmed.contains('e') || trimmed.contains('E')) && trimmed.parse::<f64>().is_ok() {
        let value = trimmed.parse::<f64>().map_err(|err| err.to_string())?;
        if let Some(number) = serde_json::Number::from_f64(value) {
            return Ok(Value::Number(number));
        }
    }
    Ok(Value::String(text.to_string()))
}

fn parse_csv(text: &str) -> Value {
    if text.trim().is_empty() {
        return Value::Array(Vec::new());
    }
    Value::Array(
        text.split(',')
            .map(|part| Value::String(part.trim().to_string()))
            .collect(),
    )
}

fn parse_color_choice(text: &str) -> Result<ColorChoice> {
    match text.to_ascii_lowercase().as_str() {
        "auto" => Ok(ColorChoice::Auto),
        "always" => Ok(ColorChoice::Always),
        "never" => Ok(ColorChoice::Never),
        _ => Err(Error::InvalidColorChoice(text.to_string())),
    }
}

fn parse_shell(text: &str) -> Result<Shell> {
    match text.to_ascii_lowercase().as_str() {
        "bash" => Ok(Shell::Bash),
        "elvish" => Ok(Shell::Elvish),
        "fish" => Ok(Shell::Fish),
        "powershell" | "power-shell" | "pwsh" => Ok(Shell::PowerShell),
        "zsh" => Ok(Shell::Zsh),
        _ => Err(Error::InvalidCompletionShell(text.to_string())),
    }
}

fn apply_choice(field: &FieldInfo, value: &Value) -> Result<()> {
    if field.choices.is_empty() {
        return Ok(());
    }
    let Some(text) = value.as_str() else {
        return Ok(());
    };
    if field.choices.iter().any(|choice| *choice == text) {
        Ok(())
    } else {
        Err(Error::Choice {
            field: field.name.to_string(),
            value: text.to_string(),
            choices: field.choices,
        })
    }
}

fn render_help(spec: &ConfigSpec) -> String {
    render_help_with_color(spec, ColorChoice::Auto)
}

fn render_help_with_color(spec: &ConfigSpec, color: ColorChoice) -> String {
    let mut cmd = build_command(spec, color);
    let help = cmd.render_help();
    if matches!(color, ColorChoice::Always) {
        help.ansi().to_string()
    } else {
        help.to_string()
    }
}

fn print_help_to_stdout(spec: &ConfigSpec, color: ColorChoice) -> std::io::Result<()> {
    let mut cmd = build_command(spec, color);
    cmd.print_help()?;
    println!();
    Ok(())
}

fn render_completion(spec: &ConfigSpec, shell: Shell, bin_name: &str) -> String {
    let mut cmd = build_command(spec, ColorChoice::Never);
    cmd.set_bin_name(bin_name.to_string());
    let mut buf = Vec::new();
    generate(shell, &mut cmd, bin_name.to_string(), &mut buf);
    String::from_utf8(buf).expect("clap completion output is UTF-8")
}

fn kwconf_help_styles() -> Styles {
    Styles::styled()
        .header(AnsiColor::Green.on_default().effects(Effects::BOLD))
        .usage(AnsiColor::Green.on_default().effects(Effects::BOLD))
        .literal(AnsiColor::Cyan.on_default().effects(Effects::BOLD))
        .placeholder(AnsiColor::Cyan.on_default())
        .error(AnsiColor::Red.on_default().effects(Effects::BOLD))
        .valid(AnsiColor::Cyan.on_default().effects(Effects::BOLD))
        .invalid(AnsiColor::Yellow.on_default().effects(Effects::BOLD))
}

fn build_command(spec: &ConfigSpec, color: ColorChoice) -> Command {
    let mut cmd = Command::new(spec.name)
        .styles(kwconf_help_styles())
        .color(color)
        .arg_required_else_help(false)
        .arg(
            Arg::new("config")
                .long("config")
                .value_name("PATH")
                .help("Read TOML, JSON, YAML, or YML config."),
        )
        .arg(
            Arg::new("generate-completion")
                .long("generate-completion")
                .value_name("SHELL")
                .value_parser(clap::value_parser!(Shell))
                .help("Generate a shell completion script."),
        )
        .arg(
            Arg::new("color")
                .long("color")
                .value_name("WHEN")
                .value_parser(["auto", "always", "never"])
                .help("Control help color: auto, always, or never."),
        );

    if let Some(about) = spec.about {
        cmd = cmd.about(about);
    }

    for field in spec.fields {
        let mut arg = Arg::new(field.name)
            .long(field.name.replace('_', "-"))
            .value_name("VALUE")
            .action(ArgAction::Set)
            .help(field_help(field));

        for alias in field.aliases {
            arg = arg.visible_alias(alias.replace('_', "-"));
        }

        if !field.choices.is_empty() {
            arg = arg.value_parser(clap::builder::PossibleValuesParser::new(field.choices.iter().copied()));
        }

        cmd = cmd.arg(arg);
    }

    cmd
}

fn field_help(field: &FieldInfo) -> String {
    let mut parts = Vec::new();
    if let Some(help) = field.help {
        parts.push(help.to_string());
    }
    if field.parser != Parser::Auto {
        parts.push(format!("parser={}", field.parser.name()));
    }
    if let Some(env) = field.env {
        parts.push(format!("env={env}"));
    }
    if !field.choices.is_empty() {
        parts.push(format!("choices={}", field.choices.join("|")));
    }
    parts.join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn auto_parser_handles_basic_scalars() {
        assert_eq!(parse_auto("true").unwrap(), Value::Bool(true));
        assert_eq!(parse_auto("3").unwrap(), Value::Number(3.into()));
        assert_eq!(parse_auto("word").unwrap(), Value::String("word".to_string()));
    }

    #[test]
    fn csv_parser_trims_parts() {
        assert_eq!(
            parse_csv("a, b,c"),
            Value::Array(vec![
                Value::String("a".to_string()),
                Value::String("b".to_string()),
                Value::String("c".to_string()),
            ])
        );
    }

    #[test]
    fn shell_parser_accepts_common_names() {
        assert_eq!(parse_shell("bash").unwrap(), Shell::Bash);
        assert_eq!(parse_shell("pwsh").unwrap(), Shell::PowerShell);
    }

    #[test]
    fn color_parser_accepts_common_names() {
        assert!(matches!(parse_color_choice("auto").unwrap(), ColorChoice::Auto));
        assert!(matches!(parse_color_choice("always").unwrap(), ColorChoice::Always));
        assert!(matches!(parse_color_choice("never").unwrap(), ColorChoice::Never));
    }
}
