//! kwconf-style CLI and config resolution for Rust.
//!
//! The runtime keeps one small contract:
//!
//! ```text
//! defaults < config file < env < argv
//! ```
//!
//! Structured sources (defaults and config files) are merged as values.
//! String-only sources (argv and env) are kept as raw text and coerced by the
//! destination field type during the final Serde deserialization, so a
//! `String` field can hold `"123"` while a `u32` field parses it.
//!
//! One `clap` command model drives argv recognition, help, and completions.

#![forbid(unsafe_code)]

mod command;
mod error;
mod resolve;
mod sources;
mod spec;
mod tree;

use serde::de::DeserializeOwned;
use serde::Serialize;
use std::ffi::OsString;

pub use clap::ColorChoice;
pub use clap_complete::aot::Shell as CompletionShell;
pub use error::{Error, Help, Result};
pub use kwconf_derive::{Config, ModalConfig};
pub use sources::Sources;

/// Derive-macro plumbing. Not part of the supported public API.
#[doc(hidden)]
pub mod __private {
    pub use serde;

    pub use crate::resolve::{resolve_modal_selection, resolve_modal_variant, ModalSelection};
    pub use crate::spec::{
        ConfigSpec, FieldInfo, FieldKind, ModalSpec, ModalVariantInfo, Parser, SpecialOptions,
        ValueType,
    };
}

/// A derived config object.
pub trait Config: Default + Serialize + DeserializeOwned + Sized {
    /// Static metadata generated by the derive macro.
    #[doc(hidden)]
    fn config_spec() -> &'static __private::ConfigSpec;

    /// Resolve this config from explicit sources.
    fn from_sources(sources: Sources) -> Result<Self> {
        resolve::resolve_config::<Self>(sources)
    }

    /// Resolve this config from explicit argv (including the program name)
    /// and the declared env bindings of the current process.
    #[allow(clippy::should_implement_trait)]
    fn from_iter<I, T>(args: I) -> Result<Self>
    where
        I: IntoIterator<Item = T>,
        T: Into<OsString>,
    {
        Self::from_sources(Sources::from_iter(args))
    }

    /// Resolve this config from the current process.
    fn try_cli() -> Result<Self> {
        Self::from_sources(Sources::new())
    }

    /// Resolve this config from the current process or exit with a user-facing message.
    fn cli() -> Self {
        Self::try_cli().unwrap_or_else(|err| exit_with(err))
    }

    /// Render help text for this config.
    ///
    /// # Panics
    ///
    /// Panics if the derived schema is invalid (see [`Error::Schema`]).
    fn help() -> String {
        Self::help_with_color(ColorChoice::Auto)
    }

    /// Render help text with an explicit color policy.
    ///
    /// # Panics
    ///
    /// Panics if the derived schema is invalid (see [`Error::Schema`]).
    fn help_with_color(color: ColorChoice) -> String {
        let spec = Self::config_spec();
        let mut model = command::build_config_model(spec, spec.name).unwrap_or_else(schema_panic);
        command::render_help(&mut model.command, color).to_string()
    }

    /// Generate a shell completion script for this config.
    ///
    /// # Panics
    ///
    /// Panics if the derived schema is invalid (see [`Error::Schema`]).
    fn completion_script(shell: CompletionShell, bin_name: &str) -> String {
        let spec = Self::config_spec();
        let model = command::build_config_model(spec, spec.name).unwrap_or_else(schema_panic);
        command::render_completion(model.command, shell, bin_name)
    }
}

/// A derived modal config enum.
pub trait ModalConfig: Sized {
    /// Static metadata generated by the derive macro.
    #[doc(hidden)]
    fn modal_spec() -> &'static __private::ModalSpec;

    /// Resolve this modal config from explicit sources.
    fn from_sources(sources: Sources) -> Result<Self>;

    /// Resolve this modal config from explicit argv (including the program
    /// name) and the declared env bindings of the current process.
    #[allow(clippy::should_implement_trait)]
    fn from_iter<I, T>(args: I) -> Result<Self>
    where
        I: IntoIterator<Item = T>,
        T: Into<OsString>,
    {
        Self::from_sources(Sources::from_iter(args))
    }

    /// Resolve this modal config from the current process.
    fn try_cli() -> Result<Self> {
        Self::from_sources(Sources::new())
    }

    /// Resolve this modal config from the current process or exit with a user-facing message.
    fn cli() -> Self {
        Self::try_cli().unwrap_or_else(|err| exit_with(err))
    }

    /// Render help text for this modal config.
    ///
    /// # Panics
    ///
    /// Panics if the derived schema is invalid (see [`Error::Schema`]).
    fn help() -> String {
        Self::help_with_color(ColorChoice::Auto)
    }

    /// Render help text with an explicit color policy.
    ///
    /// # Panics
    ///
    /// Panics if the derived schema is invalid (see [`Error::Schema`]).
    fn help_with_color(color: ColorChoice) -> String {
        let mut model = command::build_modal_model(Self::modal_spec()).unwrap_or_else(schema_panic);
        command::render_help(&mut model.command, color).to_string()
    }

    /// Generate a shell completion script for this modal config.
    ///
    /// # Panics
    ///
    /// Panics if the derived schema is invalid (see [`Error::Schema`]).
    fn completion_script(shell: CompletionShell, bin_name: &str) -> String {
        let model = command::build_modal_model(Self::modal_spec()).unwrap_or_else(schema_panic);
        command::render_completion(model.command, shell, bin_name)
    }
}

fn schema_panic<T>(err: Error) -> T {
    panic!("{err}")
}

/// Print a resolution error the way `cli()` does and exit.
fn exit_with(err: Error) -> ! {
    match err {
        Error::HelpRequested(help) => {
            if let Err(io_err) = help.print() {
                eprintln!("failed to print help: {io_err}");
            }
            std::process::exit(0);
        }
        Error::CompletionRequested(script) => {
            println!("{script}");
            std::process::exit(0);
        }
        err => {
            eprintln!("{err}");
            std::process::exit(2);
        }
    }
}
